### ISSUE TITLE
Fire burnt out while the game was in pause

### ISSUE THREAD

**Issue by rocboronat** [nuria-fl/live#3]
That makes the game harder :_)

<img width="1214" alt="screen shot 2018-05-07 at 20 35 13" src="https://user-images.githubusercontent.com/456499/39713025-39c7c4fe-5236-11e8-920e-2fffd80b268c.png">

**Comment by nuria-fl** [comment]
Well you cannot really pause a fire can you? ;)

Thanks, will fix it asap!

**Comment by rocboronat** [comment]
You're most welcome! :·)

**Comment by nuria-fl** [comment]
Fixed!

**Comment by rocboronat** [comment]
👏
