### ISSUE TITLE
Accidental lethal nap

### ISSUE THREAD

**Issue by paumoreno** [nuria-fl/live#8]
While playing in my mobile device, I wanted to go to the crafting section using the nav menu, but I accidentally pressed the "sleep" button, which sits behind the menu. I was very thirsty, and such an error caused my death and prevented me to reach the Hall of Fame.

Also, when that happened, the menu fell behind the action buttons, as shown here:

![screenshot_20180620-234232](https://user-images.githubusercontent.com/916288/41703404-6e8a4052-7533-11e8-96d5-286fc2a7358e.png)

Would it be a good idea to add a "tap safe" area around the menu to prevent accidental actions when attempting to navigate to the sections?

Another proposed alternative would be to make the menu modal: any tap outside the nav menu just closes it...

... or tabbed navigation :)

**Comment by nuria-fl** [comment]
Surviving in the wild allows no mistakes. Accidents are bound to happen. Life is hard.

Tabbed navigation coming soon :)
